name: Test Modulations with Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy pytest pytest-cov

    - name: Run tests with coverage
      run: |
        pytest -v --cov=./ "Modulation_files/AM-ASK+tests/ASK_modulation_test.py"
        pytest -v --cov=./ "Modulation_files/AM-ASK+tests/AM_modulation_test.py"
        pytest -v --cov=./ "Modulation_files/FM-FSK+tests/FM_modulation_test.py"
        pytest -v --cov=./ "Modulation_files/FM-FSK+tests/FSK_modulation_test.py"
        pytest -v --cov=./ "Modulation_files/PSK-BPSK+tests/PSK_modulation_test.py"
        pytest -v --cov=./ "Modulation_files/PSK-BPSK+tests/BPSK_modulation_test.py"
        pytest -v --cov=./ "Modulation_files/QAM-QPSK+tests/QAM_modulation_test.py"
        pytest -v --cov=./ "Modulation_files/QAM-QPSK+tests/QPSK_modulation_test.py"
